### PR TITLE
Outside world does not know about insertion point

### PR DESCRIPTION
**Pull request by sherubthakur**
A very small PR that hides the implementation details of line_buffer. Now no one knows how line_buffer is tracking insertion point.

### CODE REVIEW

**Comment by mzanrosso** [comment]
@sherubthakur - For me there is no problem with this change; let's say it's a stylistic change that can be there, like no. Let's see what others say

**Comment by sholderbach** [comment]
What are the intended semantics for the `offset()` getter? The cursor over the total string or the column? The line buffer is definitely subject to change especially for a working vi mode.

**Comment by sherubthakur** [comment]
> What are the intended semantics for the `offset()` getter? The cursor over the total string or the column?

`offset` here is the column. Do you think column/row would be better names than line/offset?

I am of the opinion that the total-string-offset idea should not really exist (at least not in the public API).

> The line buffer is definitely subject to change especially for a working vi mode.

Not really sure what you mean by this. Can you elaborate on this?

**Comment by sherubthakur** [comment]
> @sherubthakur - For me there is no problem with this change; let's say it's a stylistic change that can be there, like no. Let's see what others say

I am not sure I follow this. Are you saying that there was no problem with the earlier code? or are you saying that this is a stylistic change? If you can elaborate on this, then I can answer this better.

The rationale behind this was to hide the internal details that we use in the line buffer, as I did not really feel like there was any reason to expose them. Here are some of the benefits that I can think of that we can gain here
- the probability that any change to line buffer that impacts use changing the other parts of the codebase decreases.
- You can swap out the internal details with a completely different implementation and (if the interface does not change) then you will not need to worry about changing anything in the other parts of the codebase.
- Fewer merge conflicts.

**Comment by jntrnr** [comment]
Sure, sounds good. I'm tempted to totally remove InsertionPoint, but until then at least we can hide it more like this PR does. Thanks!

**Pull request merged**
