### PR TITLE
[Add] in-line hints

### PR DESCRIPTION
**Pull request by mzanrosso**
Implemented features:
 - optional inside line hints
 - customizable hints style
 - hints from completer
 - hints from history

Example:

Registrazione schermo 2021-07-15 alle 10 28 16

### CODE REVIEW

**Comment by fdncred** [comment]
Nice!

**Comment by mzanrosso** [comment]
Before merge, i want the inside-line hints to be optional

**Comment by fdncred** [comment]
Ya, i'd also like the hints to be dark gray/configurable but we can change that sometime in the future.

**Comment by mzanrosso** [comment]
> Ya, i'd also like the hints to be dark gray/configurable but we can change that sometime in the future.

For the configurable style it's already implemented

**Comment by mzanrosso** [comment]
> Before merge, i want the inside-line hints to be optional

Done.

**Comment by jntrnr** [comment]
@mzanrosso - taking a look now.

For the history-based hints, I was testing it by typing something like:

```
> another test
> a
```

For that second line, I should see a hint for `another test`, right?

**Comment by mzanrosso** [comment]
> @mzanrosso - taking a look now.
> 
> For the history-based hints, I was testing it by typing something like:
> 
> ```
> > another test
> > a
> ```
> 
> For that second line, I should see a hint for `another test`, right?

@jntrnr This is not my implementation fault; this is because the history file is updated only when you exit.

**Comment by jntrnr** [comment]
@mzanrosso - if I exit and restart, I still don't get a hint for the history

**Comment by mzanrosso** [comment]
> @mzanrosso - if I exit and restart, I still don't get a hint for the history

@jntrnr Sorry if it wasn't clear but you cannot enable completer and history hints at the same time

**Comment by jntrnr** [comment]
@mzanrosso - if I switch to using the history, are there other settings I need to change so that I can complete the hint?  I tried switching, but if I hit tab, it completes the completion but not the history hint.

**Comment by mzanrosso** [comment]
> @mzanrosso - if I switch to using the history, are there other settings I need to change so that I can complete the hint? I tried switching, but if I hit tab, it completes the completion but not the history hint.

@jntrnr I also noticed this when I did my implementation test; this is because I added the history support for the DefaultHinter and not for the DefaultTabHandler; this could be a next feature for the tab handler

**Comment by sholderbach** [comment]
With fish or the appropriate zsh plugin it is typically right arrow or control right arrow to complete the hint at the end of the line either fully or just the next token. This would use a separate keybinding and also restrict greyed out history hints to the end of the line during entry. Depends on what we want to achieve.

**Comment by jntrnr** [comment]
@sholderbach / @mzanrosso - sounds good, we can add just the hint, and then go back and add additional commands for doing the completions.

**Comment by mzanrosso** [comment]
@jntrnr I just noticed that if I use `.with_history(history.clone())?` it doesn't save the history in the file, do you know why this happens ?

**Comment by sholderbach** [comment]
In the current setup flushing to disk occurs on dropping the instance.

**Comment by mzanrosso** [comment]
> In the current setup flushing to disk occurs on dropping the instance.

Why don't insert an option to flush every new command ?

**Comment by sholderbach** [comment]
We could `flush()` on every `append()` but as soon as the file would be at the chosen capacity and you could not use the append function of the file system anymore, you would have to write the whole file on every `append()`. At least with the current impl.

**Comment by mzanrosso** [comment]
@sholderbach I just noticed that the problem that block us occur only when I declare two `Box::new(FileBackedHistory::with_file(5, "history.txt".into())?)`

**Comment by sholderbach** [comment]
Maintaining consistent views within our process via the FS doesn't seem right. Why would you want to use multiple history instances?

**Comment by jntrnr** [comment]
We could set it up so that you have one History instance that's protected with locks.

**Comment by mzanrosso** [comment]
Fixed.

**Comment by mzanrosso** [comment]
@jntrnr , @sholderbach let me know if we are ready to merge or if I have to modify something else; before merge I need 1sec to squash as usual.

**Comment by sholderbach** [comment]
> We could set it up so that you have one History instance that's protected with locks.

If I didn't loose track of potential consumers we basically would only have to hand out immutable views/ or iterators to the components like history browsing/search/the completion engine. Only upon finishing the `read_line` function successfully we would need the mutable access to the data structure (Or if we regularly poll for changes from other processes running reedlines) The history browsing and search are currently mutually exclusive thus them being able to be handled with mutable access to a single struct.

**Comment by sholderbach** [comment]
> @jntrnr , @sholderbach let me know if we are ready to merge or if I have to modify something else; before merge I need 1sec to squash as usual.

We typically merge as squash commits, so you don't have to explicitly squash on your side.

**Comment by mzanrosso** [comment]
> > @jntrnr , @sholderbach let me know if we are ready to merge or if I have to modify something else; before merge I need 1sec to squash as usual.
> 
> We typically merge as squash commits, so you don't have to explicitly squash on your side.

oh! this feature is new for me, I always used bitbucket and I never seen it there. let me search how It works.

**Comment by sholderbach** [comment]
image

It has it's downsides as `git branch --no-merged` won't recognize those merges

**Comment by mzanrosso** [comment]
I reworded some commit messages, nothing important here.

**Comment by jntrnr** [comment]
Agreed, let's do this in stages. For the hints themselves, this looks good.

**Pull request merged**
