### PR TITLE
[Draft][Improvement] Initial support for hints

### PR DESCRIPTION
**Pull request by mzanrosso**
Initial support for hints

Surely there is some problem with the cursor position to be solved, any help is appreciated.

### CODE REVIEW

**Comment by mzanrosso** [comment]
Currently this draft was to reach an mvp and to prove that we can add the under-buffer hints; but with @jntrnr, we agreed to start first with the in-line hints and we also discuss how to implement in a better structured way.
So don't waste too much time to understand this feature right now, thanks.

**Comment by fdncred** [comment]
How about a screenshot of what it looks like?

**Comment by mzanrosso** [comment]
> How about a screenshot of what it looks like?

test

**Comment by fdncred** [comment]
@mzanrosso That's so cool. Thanks for sharing! Hopefully it'll eventually get accepted.

**Comment by mzanrosso** [comment]
@fdncred look a the the new PR, i writed the right hinter structure; I will refactor this one based on that and hopefully I will get rid of some bugs

**Comment by sholderbach** [comment]
Would a more accurate name for the PR be (auto)suggestion list?

**Comment by mzanrosso** [comment]
> Would a more accurate name for the PR be (auto)suggestion list?

Yes we can call the functionality in many ways, basically it's an under-buffer hint list

**Comment by fdncred** [comment]
@mzanrosso I saw this the other day and thought about this PR https://github.com/marlonrichert/zsh-autocomplete

**Pull request closed without merging**
